name: ai_agent_abraxas
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.11
  - scikit-learn
  - numpy
  - flask=2.2.5
  - matplotlib
  - seaborn
  - statsmodels
  - scipy
  - pytz
  - lightgbm=4.5.0
  - xgboost=2.1.3
  - pip
  - pip:
    - tensorflow>=2.10.0  # Install via pip instead of conda
    - MetaTrader5
    - ta
    - charset-normalizer>=3.0.0
    - -r requirements.txt
    - torch